<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Reads the URL map and turns it into links and web-server rules.
 *
 * The only class that knows routes.php exists: templates ask it for links,
 * the build script asks it for Apache rules.
 *
 * @package   local_richimath
 * @copyright 2026 Richi Math
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_richimath;

class routes {
    /** @var string Marker opening the generated block in .htaccess. */
    public const BLOCK_START = '# BEGIN richimath routes (generated by scripts/build-routes.php)';

    /** @var string Marker closing it. */
    public const BLOCK_END = '# END richimath routes';

    /** @var array|null The map, read once per request. */
    private static $map = null;

    /**
     * The whole map, keyed by address.
     *
     * @return array
     */
    public static function all(): array {
        global $CFG;

        if (self::$map === null) {
            self::$map = require($CFG->dirroot . '/local/richimath/routes.php');
        }

        return self::$map;
    }

    /**
     * Whether the web server is serving the clean addresses.
     *
     * The rules live in the Moodle root .htaccess, which Apache only reads
     * with mod_rewrite and AllowOverride FileInfo Indexes. Until an
     * administrator confirms that by ticking the setting, every link points
     * at the plain Moodle URL: a server that cannot rewrite must not end up
     * with a site full of addresses nothing answers.
     *
     * @return bool
     */
    public static function enabled(): bool {
        return (bool)get_config('local_richimath', 'prettyurls');
    }

    /**
     * The link for a route: the clean address when the server serves it, the
     * real script when it does not.
     *
     * @param string $name Route key, e.g. 'students'.
     * @param array $params Query string parameters.
     * @return \moodle_url
     */
    public static function url(string $name, array $params = []): \moodle_url {
        if (!isset(self::all()[$name])) {
            throw new \coding_exception("Unknown route: {$name}");
        }

        return new \moodle_url(self::enabled() ? '/' . $name : self::target($name), $params);
    }

    /**
     * The script a route serves, as a site-relative path.
     *
     * @param string $name Route key.
     * @return string
     */
    public static function target(string $name): string {
        return self::all()[$name]['target'];
    }

    /**
     * Every real path that must end up on a pretty address, mapped to it.
     *
     * @return array Real path => route name.
     */
    public static function canonical_map(): array {
        $map = [];
        foreach (self::all() as $name => $route) {
            foreach (array_merge([$route['target']], $route['aliases'] ?? []) as $path) {
                $map[$path] = $name;
            }
        }

        return $map;
    }

    /**
     * The Apache block for every route, ready to drop into .htaccess.
     *
     * Two passes, and the order matters. First the real paths are redirected
     * to their pretty address, so a link Moodle built itself still leaves the
     * browser on the short URL. Then the pretty address is served in place by
     * the script behind it.
     *
     * The redirects are 302 and not 301 on purpose: a browser caches a 301
     * for good, so turning the clean addresses off would leave every visitor
     * who already loaded the site hitting URLs the server no longer answers.
     *
     * Two conditions guard the redirects:
     * - REDIRECT_STATUS is empty only on a request that came from outside, so
     *   the rewrite below cannot bounce back through the redirect above.
     * - POST is never redirected: browsers turn a redirected POST into a GET
     *   and drop the form data, which would break every login and every form.
     *
     * @return string
     */
    public static function apache_rules(): string {
        $lines = [
            self::BLOCK_START,
            '# Edit local/richimath/routes.php and run scripts/build-routes.php.',
            '<IfModule mod_dir.c>',
            '    # /login is a real directory, and mod_dir would 301 it to',
            '    # /login/ before the rules below ever serve it.',
            '    DirectorySlash Off',
            '</IfModule>',
            '<IfModule mod_rewrite.c>',
            '    RewriteEngine On',
            '',
            '    # 1. Real path -> pretty address, for requests that came from a browser.',
        ];

        foreach (self::canonical_map() as $path => $name) {
            // A directory alias keeps its slash on purpose: '^login/?$' would
            // also match the pretty '/login' and send it back to itself.
            $pattern = '^' . preg_quote(ltrim($path, '/'), '/') . '$';
            $lines[] = '    RewriteCond %{ENV:REDIRECT_STATUS} ^$';
            $lines[] = '    RewriteCond %{REQUEST_METHOD} !=POST';
            $lines[] = "    RewriteRule {$pattern} /{$name} [R=302,L,QSA]";
        }

        $lines[] = '';
        $lines[] = '    # 2. Pretty address -> the script that serves it, in place.';
        foreach (self::all() as $name => $route) {
            $lines[] = "    RewriteRule ^{$name}/?$ " . ltrim($route['target'], '/') . ' [L,QSA]';
        }

        $lines[] = '</IfModule>';
        $lines[] = self::BLOCK_END;

        return implode("\n", $lines) . "\n";
    }
}
